# Generated by Django 5.1.1 on 2024-10-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
